@startuml
'https://plantuml.com/class-diagram

class FileLoader {
    loadFile(): String
}

class FileWriter {
    writeFile(): void
}

class App {
    loader: FileLoader
    writer: FileWriter
}

App --* FileLoader
App --* FileWriter

@enduml